export default Locations = [
  {
    city: "Chatal / Iran",
    dateTime: "چهارشنبه 12 اسفند",
    tempDay: "26 \u2103",
    tempNight: "16 \u2103",
    weatherType: "Night",
    description: "آسمانی صاف همراه با وزش باد",
    rainPercent: 8,
    sunRise: "6:14",
    sunSet: "17:07",
    id: 1,
  },
  {
    city: "Ghapan / Iran",
    dateTime: "پنجشنبه 13 اسفند",
    tempDay: "34 \u2103",
    tempNight: "20 \u2103",
    weatherType: "Cloudy",
    description: "آسمانی با هوای ابری",
    rainPercent: 11,
    sunRise: "6:11",
    sunSet: "17:08",
    id: 2,
  },
  {
    city: "Shahr-e Faraghi / Iran",
    dateTime: "جمعه 14 فروردین",
    tempDay: "31 \u2103",
    tempNight: "18 \u2103",
    weatherType: "Sunny",
    description: "آسمانی صاف و به شدت آفتابی",
    rainPercent: 0,
    sunRise: "6:04",
    sunSet: "17:22",
    id: 3,
  },
  {
    city: "Gonbad-e Qabus / Iran",
    dateTime: "شنبه 26 اردیبهشت",
    tempDay: "15 \u2103",
    tempNight: "7 \u2103",
    weatherType: "Rainy",
    description: "آسمان ابری و بارانی",
    rainPercent: 83,
    sunRise: "6:21",
    sunSet: "17:01",
    id: 4,
  },
];
